title: CynderHost Status
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: https://status.cynderhost.com
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: Jan 2 — 15:04 UTC
  down: "#e60000"
  systems:
    - name: CynderHost Website
      category: Core Services
      description: CynderHost's Main Website and Client Area (cynderhost.com)
    - name: API (api.cynderhost.com)
      category: Core Services
    - name: CDN (StackPath)
      category: Core Services
    - name: Email Cluster
      category: Core Services
      description: Outbound email delivery infrastructure and relays
  dateFormat: January 2, 2006 at 3:04 PM UTC
  brand: "#001f3e"
  enableLastMod: true
  headerTextColor: white
  logo: https://cynderhost.com/brand/cynderhost_logo_transparent_white.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: monthly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: Core Services
      closed: false
    - name: Shared Hosting
      closed: false
    - name: High Performance Hosting
      closed: false
  description: We continuously monitor the status of our services and if there are
    any interruptions, a note will be posted here.
  enableCustomHTML: true
  useLargeHeaderDesign: true
